// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydyulgixshpavtthixrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkeXVsZ2l4c2hwYXZ0dGhpeHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTk2MTcsImV4cCI6MjA1NzI5NTYxN30.ojcsvBLtlcqsNy0t7HgczPvvGcH3-3GHLhSf1-kfyQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);